export declare enum ErrorCodeEnum {
  FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_REQUEST_INPUT = 'INVALID_REQUEST_INPUT',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  SERVICE_NOT_FOUND = 'SERVICE_NOT_FOUND',
  UNDEFINED = 'UNDEFINED',
  UNSUPPORTED_SORT = 'UNSUPPORTED_SORT',
  UNSUPPORTED_FILTER = 'UNSUPPORTED_FILTER',
}

export declare type StringObjectID = string;
